name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: 21
          cache: maven

          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build Project
        run: mvn clean install

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
